### ISSUE TITLE
No option to create .desktop shortcuts

### ISSUE THREAD

**Issue by rockerbacon** [aggalex/Wineglass#45]
The page description on the Elementary AppCenter says "Make installed apps available normally through the applications menu", however I could not find this feature anywhere.

**Comment by aggalex** [comment]
Weird. The app shows up normally inside my applications menu. Some troubleshooting steps:
- The app is currently only in the accessories section. Make sure you look in there
- xkill wingpanel, it will show up immediately again because of Cerbere, and see if it is now inside the menu
If these actions didn't do anything, please tell me the steps you took to build and run the app.

**Comment by aggalex** [comment]
This is for wine to do. Sometimes wine does not make the appropriate shortcuts (shrug). Sometimes the menu needs to be reloaded to show the new icons (xkill the panel or login/logout). I can't do anything about it right now.
